/**
 * Type definitions index
 * Central export point for all type definitions used throughout the application
 */

// 通用类型
export type {
  ApiResponse,
  PaginationResponse,
  ApiError,
} from './common.types.js';

// API 相关类型
export type {
  AuthUrlResponse,
  WorldBuildingResponse,
  GenerateOutlineRequest,
  GenerateCharacterRequest,
  PolishTextRequest,
  GenerateCharactersResponse,
  GenerateOutlineResponse,
  ChapterGenerateRequest,
  ChapterCanGenerateResponse,
  OutlineReorderItem,
  OutlineReorderRequest,
  ChapterPlanItem,
  OutlineExpansionRequest,
  OutlineExpansionResponse,
  BatchOutlineExpansionRequest,
  BatchOutlineExpansionResponse,
  TriggerAnalysisResponse,
  MCPTool,
  MCPTestResult,
  MCPToolCallRequest,
  MCPToolCallResponse,
  KeyPoolListResponse,
  KeyStats,
  KeyPoolStatsResponse,
  KeyPoolTestResult,
  PresetListResponse,
  WritingStyleListResponse,
  PresetStyle,
  ForeshadowStats,
  ForeshadowListResponse,
  PlantForeshadowRequest,
  ResolveForeshadowRequest,
  SyncFromAnalysisRequest,
  SyncFromAnalysisResponse,
  ForeshadowContextResponse,
  ChapterAnalysisResponse,
} from './api.types.js';

// 数据模型类型
export type {
  User,
  Settings,
  SettingsUpdate,
  APIKeyPresetConfig,
  APIKeyPreset,
  PresetCreateRequest,
  PresetUpdateRequest,
  Project,
  ProjectCreate,
  ProjectUpdate,
  ProjectWizardUpdate,
  ProjectWizardRequest,
  Outline,
  OutlineCreate,
  OutlineUpdate,
  Character,
  CharacterUpdate,
  ExpansionPlanData,
  Chapter,
  ChapterCreate,
  ChapterUpdate,
  WritingStyle,
  WritingStyleCreate,
  WritingStyleUpdate,
  WizardBasicInfo,
  AnalysisTask,
  AnalysisHook,
  AnalysisForeshadow,
  AnalysisConflict,
  AnalysisEmotionalArc,
  AnalysisCharacterState,
  AnalysisPlotPoint,
  AnalysisScene,
  AnalysisScores,
  AnalysisData,
  StoryMemory,
  MCPPlugin,
  MCPPluginCreate,
  MCPPluginUpdate,
  KeyPool,
  KeyPoolCreateRequest,
  KeyPoolUpdateRequest,
  ForeshadowStatus,
  ForeshadowSourceType,
  ForeshadowCategory,
  Foreshadow,
  ForeshadowCreate,
  ForeshadowUpdate,
  Genre,
  GenreCreate,
  GenreUpdate,
  GenreListResponse,
} from './models.types.js';
